ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: monthly

exclude: ^(docs|studies|tests/samples|src/awkward/_typeparser/generated_parser.py)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: name-tests-test
    args: ["--pytest-test-first"]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: e2c2116d86a80e72e7146a06e68b7c228afc6319  # frozen: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 5e2fb545eba1ea9dc051f6f962d52fe8f76a9794  # frozen: v0.15.13
  hooks:
  - id: ruff-check
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
  hooks:
  - id: codespell
    args: ["-L", "ue,subjet,parms,fo,numer,thre,nin,nout"]

- repo: local
  hooks:
  - id: disallow-caps
    name: disallow improper capitalization
    language: pygrep
    entry: PyBind|Cmake|CCache|Github|PyTest
    exclude: .pre-commit-config.yaml

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "745eface02aef23e168a8afb6b5737818efbea95"  # frozen: v0.11.0.1
  hooks:
  - id: shellcheck

- repo: local
  hooks:
  - id: require-test-name-identifier
    name: require identifiers for test names
    language: python
    entry: python dev/validate-test-names.py
    types: [file, python]
    files: ^tests/

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: f805888065fdb6162e1f800e50bb9460cbd223d6  # frozen: 0.37.2
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
    - id: mypy
      files: src
      additional_dependencies:
        - numpy>=1.24

- repo: https://github.com/abravalheri/validate-pyproject
  rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7  # frozen: v0.25
  hooks:
    - id: validate-pyproject

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: a4727cbbcd26d7098e96b9cb738169b59711ae51  # frozen: v1.24.1
  hooks:
    - id: zizmor
      files: "^\\.github"
      args: [--persona=pedantic]
