name: Sync Docs Selector

on:
  push:
    branches:
      - main
    paths:
      - docs/switcher.json
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'docs-version-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-22.04
    name: Push version switcher
    permissions:
      contents: write # Required to push the version selector to the `gh-pages` branch.
    environment:
      name: docs
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # Pushes to main trigger latest
      - name: Push version selector
        uses: ./.github/actions/deploy-to-gh-pages
        with:
          source: docs/switcher.json
          target: doc/switcher.json
          message: "Deploy version selector"
          token: ${{ secrets.GITHUB_TOKEN }}
