name: Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pylint:
    name: "Run PyLint"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true
        persist-credentials: false

    - name: Run PyLint
      run: |
        echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
        pipx run nox -s pylint
