name: Lint

on:
  pull_request:
  workflow_dispatch:


concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pylint:
    name: "Run PyLint"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true
        persist-credentials: false

    - name: Run PyLint
      run: |
        echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
        pipx run nox -s pylint
